-- Migration 075: Seed the 188 bus stops + their 2025-26 monthly fees.
--
-- Source: NK Public School "List of Bus Fee [Session 2025-26]" (dated 01/04/2025).
-- Stops are the stable master (name = identity); the amount is stored per
-- academic year in bus_stop_fees so it can be re-priced ("fare may rise with
-- diesel") without re-entering stops. Target year resolves to '2025-26' if it
-- exists, else the current year. Fully idempotent (re-runnable).

begin;

-- 1. Stops (stable registry). sort_order mirrors the sheet's serial number.
insert into bus_stops (name, sort_order) values
  ('100 Feet Road', 1),
  ('34 No. Bus Stand, Niwaru Road', 2),
  ('4 C Road', 3),
  ('80 Feet Road, Niwaru Road', 4),
  ('Adarsh Vidhya Mandir, Jhotwara', 5),
  ('Adrash Vidhya Mandir, Ambari', 6),
  ('Agarasen Apartment', 7),
  ('Agarwal Caters, Ambabari', 8),
  ('Akshat Govind Dham, Benar Road', 9),
  ('Alka Cinema, Sikar Road', 10),
  ('Alka Puri, Murlipura', 11),
  ('Ambabari', 12),
  ('Anaj Mandi, By Pass Road', 13),
  ('Anantpura', 14),
  ('Anand Chauraha', 15),
  ('Anchal Paridhan, Dadi ka Phatak', 16),
  ('Anokha Gaun, Sikar Road', 17),
  ('Apno Gaun', 18),
  ('Bad Pipli', 19),
  ('Badarna Sabji Mandi', 20),
  ('Bajrang Dawar', 21),
  ('Balaji College', 22),
  ('Balaji Dharam Kanta, Sikar Road', 23),
  ('Balaji Phatak, Benar Road', 24),
  ('Benar Rail Way Station', 25),
  ('Bhairu Khejra', 26),
  ('Bhato Ki Gali', 27),
  ('Bhawani Nagar, Murlipura', 28),
  ('Bhawani Niketan School & College', 29),
  ('Bhomiya ji ka mandir', 30),
  ('Boring Road', 31),
  ('Brij Bal Vidhya Mandir, Jhotwara', 32),
  ('Budaniya Chauraha, Murlipura', 33),
  ('Chand Bihari Nagar Mode', 34),
  ('Chomu', 35),
  ('Chomu Puliya', 36),
  ('Cine Star V.D.N., Sec.-6', 37),
  ('D.P.S. School, V.D.N.', 38),
  ('Dadi ka Phatak', 39),
  ('Dadi ka Phatak (By Pass)', 40),
  ('Dev Guda', 41),
  ('Doodh Mandi', 42),
  ('Dwarika Tower, V.D.N., Sec-1', 43),
  ('Eden Garden', 44),
  ('Gadliyon Ki Dhani', 45),
  ('Gandhi Bal Niketan', 46),
  ('Ganesh Mandir, Khirni Phatak Road', 47),
  ('Ganesh Nagar Vistar, Benar Road', 48),
  ('Ganesh Nagar, Charan Nadi-II', 49),
  ('Ghodela Brother''s', 50),
  ('Gouras Bhandar', 51),
  ('Govindpura', 52),
  ('Manglam Vihar, Sikar Road', 53),
  ('Govt. Sec. School, Charan Nadi-II', 54),
  ('Govt. School, Charan Nadi-I', 55),
  ('Govt. School, Murlipura Scheme', 56),
  ('Green Park', 57),
  ('Gyan Jyoti School, Murlipura', 58),
  ('Hari Nagar, Shastri Nagar', 59),
  ('Harmara', 60),
  ('Harmara Ghati By Pass, Sikar Road', 61),
  ('Harnath Pura, Kalwar Road', 62),
  ('ICICI Bank, V.D.N., Sec-6', 63),
  ('J.P. Colony, Naya Khera', 64),
  ('Jahota', 65),
  ('Jairampura', 66),
  ('Jaitpura', 67),
  ('Jakhar Mode, S.B.N School, Murlipura', 68),
  ('Jalsu', 69),
  ('Jangid Nagri, Charan Nadi-I', 70),
  ('Jaswant Nagar Mode', 71),
  ('Jhotwara Circle', 72),
  ('Jhotwara Thana', 73),
  ('Jodla Power House, Sikar Road', 74),
  ('Joshi Marg', 75),
  ('Jwala Mata Mandir, Benar Road', 76),
  ('Kalwar Pulia', 77),
  ('Kamani Chauraha', 78),
  ('Kamani Petrol Pump', 79),
  ('Kanta, Jhotwara', 80),
  ('Kardhani, Govindam Towar', 81),
  ('Kaushik School, Green Park', 82),
  ('Kedia Palace, Murlipura', 83),
  ('Kedia Pulia, By Pass Road', 84),
  ('Khandelwal Tower, New Kheda', 85),
  ('Khatipura', 86),
  ('Khatipura Pulia', 87),
  ('Khetan Hospital', 88),
  ('Khirni Phatak', 89),
  ('Khora', 90),
  ('Khora Shyamdas', 91),
  ('Kumawat Colony', 92),
  ('Lal Dibb''a Murlipura Scheme', 93),
  ('Lata Cinema', 94),
  ('Laxmi Nagar, Niwaru Road', 95),
  ('Loha Mandi', 96),
  ('Loha Mandi Mode, By Pass Road', 97),
  ('M.G.P.S. Biyani, V.D.N, Sec-1', 98),
  ('Machara Gaun', 99),
  ('Maharana Pratap School, Jhotwara', 100),
  ('Major Shaitan Singh Colony', 101),
  ('Mandir Road Vidhaydhar Nagar', 102),
  ('Mata Ji ka Mandir, 34 No. Bus Stand', 103),
  ('Medical Centre, Jhotwara', 104),
  ('Meena Ki Dhani, By Pass Road', 105),
  ('Modi', 106),
  ('Mother Land Public School, Niwaru', 107),
  ('Murlipura Circle', 108),
  ('Murlipura Thana', 109),
  ('N.K. Public School, Murlipura', 110),
  ('Nadi ka Phatak', 111),
  ('Nangal Jaisa Bohara', 112),
  ('Nangal Jaisa Bohara Mode', 113),
  ('Nangal Purohitan, Rajawas', 114),
  ('Nangal Siras', 115),
  ('Narmda Hospital, Murlipura', 116),
  ('Nath Ji Ki Thadi, Niwaru Road', 117),
  ('National Handloom V.D.N., Sec.-3', 118),
  ('Neta Ji Ki Chakki, Niwaru Road', 119),
  ('Nindar Gaun', 120),
  ('Nindar Mode, Sikar Road', 121),
  ('Nirmal Vihar, Benar Road', 122),
  ('Niwaru', 123),
  ('Niwaru Mode (By Pass Road)', 124),
  ('Old Vidhyadhar Nagar Bus Stand', 125),
  ('P.N.B., Dehar Ka Balaji', 126),
  ('Palak Paradise', 127),
  ('Pani Pench Tiraha', 128),
  ('Pankha, Jhotwara', 129),
  ('Papad Ka Hanuman Ji V.D.N.', 130),
  ('Pawan Puri, Nadi Ka Phatak', 131),
  ('Pratap Nagar Chauraha, Murlipura', 132),
  ('Pratap Nagar, Shastri Nagar', 133),
  ('Prem Nagar (Burtal)', 134),
  ('Prem Nagar, Jhotwara', 135),
  ('Pushpanjali Marriage Garden', 136),
  ('R.P.A., Shastri Nagar', 137),
  ('Radha Swami Baag', 138),
  ('Rail Vihar V.D.N. Sec-2', 139),
  ('Rajarampura', 140),
  ('Rajawas', 141),
  ('Ram Nagar, Jhotwara', 142),
  ('Rameshwar Dham, Murlipura', 143),
  ('Ramnesh Puri, Niwaru Road', 144),
  ('Rampura Dabri & Toll', 145),
  ('Ratan Pan Bhandar, Balaji Hospital', 146),
  ('Road No.-12 (Main Sikar Road)', 147),
  ('Road No.-14 (Main Sikar Road)', 148),
  ('Road No.-14, Milan Cinema', 149),
  ('Road No.-2, Bus Stand', 150),
  ('Road No.-8 (Main Sikar Road)', 151),
  ('Road No.-9-A (Main Sikar Road)', 152),
  ('Road No.-9-B (Main Sikar Road)', 153),
  ('Road No-5 (Main Sikar Road)', 154),
  ('Road Ways Bus Depo', 155),
  ('Rose Public School, Murlipura', 156),
  ('S.D. Agarwal, Jhotwara', 157),
  ('Sahara Ayourvadik Hospital', 158),
  ('Sanjay Nagar, Niwaru Road', 159),
  ('Science Park, Shastri Nagar', 160),
  ('Sec-10, V.D.N.', 161),
  ('Senapati House, Jhotwara', 162),
  ('Shakti Nagar, Niwaru Road', 163),
  ('Shalimar Chauraha', 164),
  ('Shastri Nagar Circle', 165),
  ('Shastri Nagar Circle [Shani Mandir]', 166),
  ('Shiv Nagar-II, Murlipura', 167),
  ('Shyam Mandir, Path No.-7', 168),
  ('Shyam Mandir, Road No.-5', 169),
  ('Shyam Nagar Mode, Benar Road', 170),
  ('Sindhu Nagar, Murlipura', 171),
  ('Sita Ram Puri, By Pass Road', 172),
  ('Sun & Moon, Sikar Road', 173),
  ('Sun City Projects', 174),
  ('Surya Nagar, Benar Road', 175),
  ('Tara Nagar', 176),
  ('Teja ji ka Mandir, Jhotwara', 177),
  ('Time Squayar V.D.N.', 178),
  ('Tirupati Nilay', 179),
  ('Todi Harmara', 180),
  ('Vaid Ji Ka Chauraha, Murlipura', 181),
  ('Vaid Ji Ka Chauraha, Niwaru Road', 182),
  ('Vaishnav Vihar, Green Park', 183),
  ('Vidhydhar Nagar Thana, Sec-2', 184),
  ('Vijay Childrens Academy, Loha Mandi', 185),
  ('Vikas Nagar, Murlipura', 186),
  ('Vikas Vidhya Asharam', 187),
  ('Water Tank, Murlipura', 188)
on conflict (name) do nothing;

-- 2. Per-year fees for the resolved academic year.
insert into bus_stop_fees (bus_stop_id, academic_year_id, amount, frequency)
select bs.id, ty.id, v.amount, 'monthly'
from (values
  ('100 Feet Road', 1500),
  ('34 No. Bus Stand, Niwaru Road', 1500),
  ('4 C Road', 1500),
  ('80 Feet Road, Niwaru Road', 1500),
  ('Adarsh Vidhya Mandir, Jhotwara', 1550),
  ('Adrash Vidhya Mandir, Ambari', 1550),
  ('Agarasen Apartment', 1500),
  ('Agarwal Caters, Ambabari', 1500),
  ('Akshat Govind Dham, Benar Road', 1500),
  ('Alka Cinema, Sikar Road', 1450),
  ('Alka Puri, Murlipura', 1450),
  ('Ambabari', 1650),
  ('Anaj Mandi, By Pass Road', 1500),
  ('Anantpura', 1450),
  ('Anand Chauraha', 1500),
  ('Anchal Paridhan, Dadi ka Phatak', 1450),
  ('Anokha Gaun, Sikar Road', 1450),
  ('Apno Gaun', 1450),
  ('Bad Pipli', 950),
  ('Badarna Sabji Mandi', 1500),
  ('Bajrang Dawar', 1650),
  ('Balaji College', 1500),
  ('Balaji Dharam Kanta, Sikar Road', 1430),
  ('Balaji Phatak, Benar Road', 1500),
  ('Benar Rail Way Station', 1500),
  ('Bhairu Khejra', 1450),
  ('Bhato Ki Gali', 1500),
  ('Bhawani Nagar, Murlipura', 1450),
  ('Bhawani Niketan School & College', 1500),
  ('Bhomiya ji ka mandir', 1450),
  ('Boring Road', 1500),
  ('Brij Bal Vidhya Mandir, Jhotwara', 1450),
  ('Budaniya Chauraha, Murlipura', 1450),
  ('Chand Bihari Nagar Mode', 1700),
  ('Chomu', 1500),
  ('Chomu Puliya', 1500),
  ('Cine Star V.D.N., Sec.-6', 1500),
  ('D.P.S. School, V.D.N.', 1500),
  ('Dadi ka Phatak', 1450),
  ('Dadi ka Phatak (By Pass)', 1450),
  ('Dev Guda', 1600),
  ('Doodh Mandi', 1650),
  ('Dwarika Tower, V.D.N., Sec-1', 1500),
  ('Eden Garden', 650),
  ('Gadliyon Ki Dhani', 1500),
  ('Gandhi Bal Niketan', 1450),
  ('Ganesh Mandir, Khirni Phatak Road', 1600),
  ('Ganesh Nagar Vistar, Benar Road', 1550),
  ('Ganesh Nagar, Charan Nadi-II', 1500),
  ('Ghodela Brother''s', 1450),
  ('Gouras Bhandar', 1450),
  ('Govindpura', 1750),
  ('Manglam Vihar, Sikar Road', 1450),
  ('Govt. Sec. School, Charan Nadi-II', 1500),
  ('Govt. School, Charan Nadi-I', 1500),
  ('Govt. School, Murlipura Scheme', 1450),
  ('Green Park', 1430),
  ('Gyan Jyoti School, Murlipura', 1450),
  ('Hari Nagar, Shastri Nagar', 1600),
  ('Harmara', 1450),
  ('Harmara Ghati By Pass, Sikar Road', 1450),
  ('Harnath Pura, Kalwar Road', 1650),
  ('ICICI Bank, V.D.N., Sec-6', 1500),
  ('J.P. Colony, Naya Khera', 1500),
  ('Jahota', 1500),
  ('Jairampura', 1450),
  ('Jaitpura', 1450),
  ('Jakhar Mode, S.B.N School, Murlipura', 1450),
  ('Jalsu', 1650),
  ('Jangid Nagri, Charan Nadi-I', 1500),
  ('Jaswant Nagar Mode', 1700),
  ('Jhotwara Circle', 1500),
  ('Jhotwara Thana', 1500),
  ('Jodla Power House, Sikar Road', 1450),
  ('Joshi Marg', 1500),
  ('Jwala Mata Mandir, Benar Road', 1500),
  ('Kalwar Pulia', 1500),
  ('Kamani Chauraha', 1500),
  ('Kamani Petrol Pump', 1500),
  ('Kanta, Jhotwara', 1500),
  ('Kardhani, Govindam Towar', 1750),
  ('Kaushik School, Green Park', 1450),
  ('Kedia Palace, Murlipura', 1450),
  ('Kedia Pulia, By Pass Road', 1450),
  ('Khandelwal Tower, New Kheda', 1500),
  ('Khatipura', 1750),
  ('Khatipura Pulia', 1500),
  ('Khetan Hospital', 1450),
  ('Khirni Phatak', 1700),
  ('Khora', 1500),
  ('Khora Shyamdas', 1500),
  ('Kumawat Colony', 1500),
  ('Lal Dibb''a Murlipura Scheme', 1450),
  ('Lata Cinema', 1500),
  ('Laxmi Nagar, Niwaru Road', 1500),
  ('Loha Mandi', 1450),
  ('Loha Mandi Mode, By Pass Road', 1450),
  ('M.G.P.S. Biyani, V.D.N, Sec-1', 1500),
  ('Machara Gaun', 1500),
  ('Maharana Pratap School, Jhotwara', 1500),
  ('Major Shaitan Singh Colony', 1650),
  ('Mandir Road Vidhaydhar Nagar', 1500),
  ('Mata Ji ka Mandir, 34 No. Bus Stand', 1500),
  ('Medical Centre, Jhotwara', 1500),
  ('Meena Ki Dhani, By Pass Road', 1500),
  ('Modi', 1500),
  ('Mother Land Public School, Niwaru', 1500),
  ('Murlipura Circle', 1450),
  ('Murlipura Thana', 1450),
  ('N.K. Public School, Murlipura', 1450),
  ('Nadi ka Phatak', 1450),
  ('Nangal Jaisa Bohara', 1500),
  ('Nangal Jaisa Bohara Mode', 1460),
  ('Nangal Purohitan, Rajawas', 1000),
  ('Nangal Siras', 1350),
  ('Narmda Hospital, Murlipura', 1450),
  ('Nath Ji Ki Thadi, Niwaru Road', 1500),
  ('National Handloom V.D.N., Sec.-3', 1500),
  ('Neta Ji Ki Chakki, Niwaru Road', 1500),
  ('Nindar Gaun', 1500),
  ('Nindar Mode, Sikar Road', 1450),
  ('Nirmal Vihar, Benar Road', 1500),
  ('Niwaru', 1650),
  ('Niwaru Mode (By Pass Road)', 1500),
  ('Old Vidhyadhar Nagar Bus Stand', 1500),
  ('P.N.B., Dehar Ka Balaji', 1480),
  ('Palak Paradise', 1500),
  ('Pani Pench Tiraha', 1650),
  ('Pankha, Jhotwara', 1500),
  ('Papad Ka Hanuman Ji V.D.N.', 1500),
  ('Pawan Puri, Nadi Ka Phatak', 1500),
  ('Pratap Nagar Chauraha, Murlipura', 1450),
  ('Pratap Nagar, Shastri Nagar', 1650),
  ('Prem Nagar (Burtal)', 1400),
  ('Prem Nagar, Jhotwara', 1500),
  ('Pushpanjali Marriage Garden', 1450),
  ('R.P.A., Shastri Nagar', 1650),
  ('Radha Swami Baag', 1480),
  ('Rail Vihar V.D.N. Sec-2', 1450),
  ('Rajarampura', 1310),
  ('Rajawas', 750),
  ('Ram Nagar, Jhotwara', 1500),
  ('Rameshwar Dham, Murlipura', 1450),
  ('Ramnesh Puri, Niwaru Road', 1500),
  ('Rampura Dabri & Toll', 1350),
  ('Ratan Pan Bhandar, Balaji Hospital', 1475),
  ('Road No.-12 (Main Sikar Road)', 1400),
  ('Road No.-14 (Main Sikar Road)', 1400),
  ('Road No.-14, Milan Cinema', 1350),
  ('Road No.-2, Bus Stand', 1450),
  ('Road No.-8 (Main Sikar Road)', 1400),
  ('Road No.-9-A (Main Sikar Road)', 1400),
  ('Road No.-9-B (Main Sikar Road)', 1400),
  ('Road No-5 (Main Sikar Road)', 1400),
  ('Road Ways Bus Depo', 1450),
  ('Rose Public School, Murlipura', 1450),
  ('S.D. Agarwal, Jhotwara', 1500),
  ('Sahara Ayourvadik Hospital', 1450),
  ('Sanjay Nagar, Niwaru Road', 1500),
  ('Science Park, Shastri Nagar', 1650),
  ('Sec-10, V.D.N.', 1500),
  ('Senapati House, Jhotwara', 1500),
  ('Shakti Nagar, Niwaru Road', 1500),
  ('Shalimar Chauraha', 1500),
  ('Shastri Nagar Circle', 1650),
  ('Shastri Nagar Circle [Shani Mandir]', 1650),
  ('Shiv Nagar-II, Murlipura', 1450),
  ('Shyam Mandir, Path No.-7', 1450),
  ('Shyam Mandir, Road No.-5', 1450),
  ('Shyam Nagar Mode, Benar Road', 1450),
  ('Sindhu Nagar, Murlipura', 1450),
  ('Sita Ram Puri, By Pass Road', 1450),
  ('Sun & Moon, Sikar Road', 1450),
  ('Sun City Projects', 950),
  ('Surya Nagar, Benar Road', 1450),
  ('Tara Nagar', 1650),
  ('Teja ji ka Mandir, Jhotwara', 1500),
  ('Time Squayar V.D.N.', 1500),
  ('Tirupati Nilay', 1050),
  ('Todi Harmara', 1050),
  ('Vaid Ji Ka Chauraha, Murlipura', 1450),
  ('Vaid Ji Ka Chauraha, Niwaru Road', 1500),
  ('Vaishnav Vihar, Green Park', 1500),
  ('Vidhydhar Nagar Thana, Sec-2', 1500),
  ('Vijay Childrens Academy, Loha Mandi', 1450),
  ('Vikas Nagar, Murlipura', 1450),
  ('Vikas Vidhya Asharam', 1450),
  ('Water Tank, Murlipura', 1450)
) as v(name, amount)
join bus_stops bs on bs.name = v.name
cross join (
  select id from academic_years
  order by (name = '2025-26') desc, is_current desc nulls last
  limit 1
) ty
on conflict (bus_stop_id, academic_year_id) do nothing;

commit;
